### PR TITLE
Optionally initialize Github repository.

### PR DESCRIPTION
**Pull request by tbpalsulich**
Uses another gem: Hub. https://github.com/github/hub

Edit: Updated to use a curl request instead of Hub.

### CODE REVIEW

**Comment by davidcelis** [comment]
:-1: on this. Bundling a gem into the Gemfile for the sole purpose of a one time event (creating a GitHub repo) seems excessive.

**Comment by rubiconvvv** [comment]
use shell commands for making github repo instead.

**Comment by tbpalsulich** [comment]
Good point! I took out the gem and created the repo with a curl request. Should we leave the output from the commands? Right now, the JSON response and git push info is printed.

**Comment by rubiconvvv** [comment]
Nice. @dennybritz what you say?

**Comment by dennybritz** [comment]
Great, thanks! Good job with the curl, I like it. I just tested it and it works.

**Pull request merged**
