### PR TITLE
Install bootstrap and font-awesome from gems

### PR DESCRIPTION
**Pull request by davidcelis**
Often, it's much easier to update assets such as Bootstrap and Font-Awesome
when they are installed from gems rather than source. Install bootstrap from
anjlab/bootstrap-rails and Font Awesome from bokmann/font-awesome-rails.

I'm guessing you installed these assets from source for a reason, but I figured
I'd submit a PR anyway.

Signed-off-by: David Celis me@davidcel.is

### CODE REVIEW

**Comment by dennybritz** [comment]
Thanks for the request. I can see the benefits of using the gems, but I'm always kind of paranoid about using "non-official" gems for any kind of assets. When are they being updated? How do I know there are no weird conflicts with other gems, etc? That's why I download them manually instead of using the gems. That way I can debug things easily and know exactly what's going on.

**Comment by dennybritz** [comment]
I also like the fact that I can search the CSS if I add the assets myself.

**Comment by davidcelis** [comment]
Hmm, my experience with the asset gems has been that they update the assets pretty quickly. People are usually quick to offer up a PR that updates the included assets on the same day. I've never had issues with conflicts, but wouldn't you get the same conflicts if you tried to use various assets without the gems? The gem is just a wrapper.

The searching through CSS is valid, but since the gems are just engines that contain the CSS assets, you can still search through them. They'll just be in your bundle instead. I suppose this is a problem if you exclude your bundle from searches

**Comment by dennybritz** [comment]
Fair points. I don't think using gems is inherently worse (or better) than manually including the assets. It probably comes down to personal choice. I always try to keep external dependencies at a minimum, that's why I'm not a huge fan of these wrapper gems. Like you said, they are just wrappers, so they don't provide a huge value add. I understand your reasons for using them and don't think it's bad, but I'd like to keep the manual asset downloads in here for now...

**Pull request closed without merging**
